//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShagOxServer.Application.Resources.Auth.Contacts.Passwords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordAuthResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordAuthResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShagOxServer.Application.Resources.Auth.Contacts.Passwords.PasswordAuthResources", typeof(PasswordAuthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change pasword..
        /// </summary>
        internal static string FailedToChangePassword {
            get {
                return ResourceManager.GetString("FailedToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset pasword..
        /// </summary>
        internal static string FailedToResetPassword {
            get {
                return ResourceManager.GetString("FailedToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contact type..
        /// </summary>
        internal static string InvalidContactType {
            get {
                return ResourceManager.GetString("InvalidContactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is incorrect..
        /// </summary>
        internal static string InvalidNewPassword {
            get {
                return ResourceManager.GetString("InvalidNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have a confirmed email or phone..
        /// </summary>
        internal static string NoConfirmedContact {
            get {
                return ResourceManager.GetString("NoConfirmedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have a confirmed email..
        /// </summary>
        internal static string UserDoesNotHaveConfirmedEmail {
            get {
                return ResourceManager.GetString("UserDoesNotHaveConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No confirmed email or phone found..
        /// </summary>
        internal static string UserDoesNotHaveConfirmedEmailOrPhone {
            get {
                return ResourceManager.GetString("UserDoesNotHaveConfirmedEmailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have a confirmed phone..
        /// </summary>
        internal static string UserDoesNotHaveConfirmedPhone {
            get {
                return ResourceManager.GetString("UserDoesNotHaveConfirmedPhone", resourceCulture);
            }
        }
    }
}
