<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.12" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="Twilio" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShagOxServer.Domain\ShagOxServer.Domain.csproj" />
    <ProjectReference Include="..\ShagOxServer.SharedKernel\ShagOxServer.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Auth\Contacts\Emails\EmailAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Contacts\Phones\PhoneAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PhoneAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Contacts\UserNames\UserNameAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserNameAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\External\Google\GoogleAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GoogleAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Logins\LoginAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LoginAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Contacts\Passwords\PasswordAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PasswordAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Registrations\RegistrationAuthResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RegistrationAuthResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Messaging\Email\EmailTemplatesResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailTemplatesResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\EntityErrorResourcess\EntityErrorResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EntityErrorResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Messaging\Sms\SmsTemplatesResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SmsTemplatesResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Verifications\Codes\VerificationCodeResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VerificationCodeResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Verifications\Core\VerificationResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VerificationResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Verifications\Mappers\VerificationMapperResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VerificationMapperResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Auth\Contacts\Emails\EmailAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>EmailAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Contacts\Phones\PhoneAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>PhoneAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Contacts\UserNames\UserNameAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>UserNameAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\External\Google\GoogleAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>GoogleAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Logins\LoginAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>LoginAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Contacts\Passwords\PasswordAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>PasswordAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Registrations\RegistrationAuthResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>RegistrationAuthResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Messaging\Email\EmailTemplatesResources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>EmailTemplatesResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\EntityErrorResourcess\EntityErrorResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>EntityErrorResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Messaging\Sms\SmsTemplatesResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>SmsTemplatesResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Verifications\Codes\VerificationCodeResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>VerificationCodeResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Verifications\Core\VerificationResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>VerificationResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Verifications\Mappers\VerificationMapperResources.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>VerificationMapperResources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	
</Project>
