<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.11" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.12" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    <PackageReference Include="Twilio" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShagOxServer.Domain\ShagOxServer.Domain.csproj" />
    <ProjectReference Include="..\ShagOxServer.SharedKernel\ShagOxServer.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Auth\Contacts\Emails\EmailAuth.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmailAuth.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Contacts\Phones\Phone.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Phone.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Contacts\UserNames\UserName.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UserName.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\External\Google\GoogleAuth.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GoogleAuth.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Logins\Login.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Login.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Contacts\Passwords\PasswordAuth.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PasswordAuth.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Auth\Registrations\Registration.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Registration.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\EmailService\Emails.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Emails.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\EntityErrors\EntityError.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EntityError.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Verifications\Codes\VerificationCode.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VerificationCode.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Verifications\Verification.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Verification.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Verifications\VerificationMapper.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>VerificationMapper.resx</DependentUpon>
    </Compile>
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Auth\Contacts\Emails\EmailAuth.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>EmailAuth.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Contacts\Phones\Phone.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Phone.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Contacts\UserNames\UserName.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>UserName.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\External\Google\GoogleAuth.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>GoogleAuth.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Logins\Login.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Login.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Contacts\Passwords\PasswordAuth.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>PasswordAuth.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Auth\Registrations\Registration.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Registration.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\EmailService\Emails.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Emails.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\EntityErrors\EntityError.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>EntityError.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Verifications\Codes\VerificationCode.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>VerificationCode.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Verifications\Verification.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>Verification.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Verifications\VerificationMapper.resx">
		  <Generator>ResXFileCodeGenerator</Generator>
		  <LastGenOutput>VerificationMapper.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	
</Project>
