#  PostgreSQL
local   all             all                             scram-sha-256

# Docker
host    all             all             172.20.0.0/16  scram-sha-256

# replication user
host    replication     replicator      172.20.0.0/16  scram-sha-256

host    all             all             127.0.0.1/32    scram-sha-256