# Local connections
local   all             all                             scram-sha-256

# Docker network
host    all             all             172.19.0.0/16  scram-sha-256

# Streaming replication
host    replication     replicator      172.19.0.0/16  scram-sha-256

# Localhost
host    all             all             127.0.0.1/32    scram-sha-256