//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShagOxServer.Application.Resources.EntityErrors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntityErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityErrorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShagOxServer.Application.Resources.EntityErrors.EntityErrorResources", typeof(EntityErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create advertisement..
        /// </summary>
        internal static string AdvertisementCreateFailed {
            get {
                return ResourceManager.GetString("AdvertisementCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete advertisement.
        /// </summary>
        internal static string AdvertisementDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertisementDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update advertisement..
        /// </summary>
        internal static string AdvertisementUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertisementUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create advertisement variant..
        /// </summary>
        internal static string AdvertisementVariantCreateFailed {
            get {
                return ResourceManager.GetString("AdvertisementVariantCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete advertisement variant..
        /// </summary>
        internal static string AdvertisementVariantDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertisementVariantDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update advertisement variant..
        /// </summary>
        internal static string AdvertisementVariantUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertisementVariantUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create status..
        /// </summary>
        internal static string AdvertStatusCreateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete status..
        /// </summary>
        internal static string AdvertStatusDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertStatusDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create status translation..
        /// </summary>
        internal static string AdvertStatusTranslationCreateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete status translation..
        /// </summary>
        internal static string AdvertStatusTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertStatusTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update status translation..
        /// </summary>
        internal static string AdvertStatusTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update status..
        /// </summary>
        internal static string AdvertStatusUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create attribute definition..
        /// </summary>
        internal static string AttributeDefinitionCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attribute definition..
        /// </summary>
        internal static string AttributeDefinitionDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create attribute definition translation..
        /// </summary>
        internal static string AttributeDefinitionTranslationCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attribute definition translation..
        /// </summary>
        internal static string AttributeDefinitionTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attribute definition translation..
        /// </summary>
        internal static string AttributeDefinitionTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attribute definition..
        /// </summary>
        internal static string AttributeDefinitionUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create attribute dictionary..
        /// </summary>
        internal static string AttributeDictionaryCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attribute dictionary..
        /// </summary>
        internal static string AttributeDictionaryDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attribute dictionary..
        /// </summary>
        internal static string AttributeDictionaryUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create attribute dictionary value..
        /// </summary>
        internal static string AttributeDictionaryValueCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryValueCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attribute dictionary value..
        /// </summary>
        internal static string AttributeDictionaryValueDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryValueDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create attribute dictionary value translation..
        /// </summary>
        internal static string AttributeDictionaryValueTranslationCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryValueTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete attribute dictionary value translation..
        /// </summary>
        internal static string AttributeDictionaryValueTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryValueTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attribute dictionary value translation..
        /// </summary>
        internal static string AttributeDictionaryValueTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryValueTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attribute dictionary value..
        /// </summary>
        internal static string AttributeDictionaryValueUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDictionaryValueUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create avatar..
        /// </summary>
        internal static string AvatarCreateFailed {
            get {
                return ResourceManager.GetString("AvatarCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete avatar..
        /// </summary>
        internal static string AvatarDeleteFailed {
            get {
                return ResourceManager.GetString("AvatarDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update avatar..
        /// </summary>
        internal static string AvatarUpdateFailed {
            get {
                return ResourceManager.GetString("AvatarUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create basket attribute..
        /// </summary>
        internal static string BasketAttributeCreateFailed {
            get {
                return ResourceManager.GetString("BasketAttributeCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete basket attribute..
        /// </summary>
        internal static string BasketAttributeDeleteFailed {
            get {
                return ResourceManager.GetString("BasketAttributeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update attribute..
        /// </summary>
        internal static string BasketAttributeUpdateFailed {
            get {
                return ResourceManager.GetString("BasketAttributeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create basket..
        /// </summary>
        internal static string BasketCreateFailed {
            get {
                return ResourceManager.GetString("BasketCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete basket..
        /// </summary>
        internal static string BasketDeleteFailed {
            get {
                return ResourceManager.GetString("BasketDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create basket item..
        /// </summary>
        internal static string BasketItemCreateFailed {
            get {
                return ResourceManager.GetString("BasketItemCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete basket item..
        /// </summary>
        internal static string BasketItemDeleteFailed {
            get {
                return ResourceManager.GetString("BasketItemDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update basket item..
        /// </summary>
        internal static string BasketItemUpdateFailed {
            get {
                return ResourceManager.GetString("BasketItemUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update basket..
        /// </summary>
        internal static string BasketUpdateFailed {
            get {
                return ResourceManager.GetString("BasketUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create category..
        /// </summary>
        internal static string CategoryCreateFailed {
            get {
                return ResourceManager.GetString("CategoryCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete category..
        /// </summary>
        internal static string CategoryDeleteFailed {
            get {
                return ResourceManager.GetString("CategoryDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create category translation..
        /// </summary>
        internal static string CategoryTranslationCreateFailed {
            get {
                return ResourceManager.GetString("CategoryTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete category translation..
        /// </summary>
        internal static string CategoryTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("CategoryTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update category translation..
        /// </summary>
        internal static string CategoryTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("CategoryTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update category..
        /// </summary>
        internal static string CategoryUpdateFailed {
            get {
                return ResourceManager.GetString("CategoryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create city..
        /// </summary>
        internal static string CityCreateFailed {
            get {
                return ResourceManager.GetString("CityCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete city..
        /// </summary>
        internal static string CityDeleteFailed {
            get {
                return ResourceManager.GetString("CityDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create city translation..
        /// </summary>
        internal static string CityTranslationCreateFailed {
            get {
                return ResourceManager.GetString("CityTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete city translation..
        /// </summary>
        internal static string CityTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("CityTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update city translation..
        /// </summary>
        internal static string CityTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("CityTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update city..
        /// </summary>
        internal static string CityUpdateFailed {
            get {
                return ResourceManager.GetString("CityUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create condition..
        /// </summary>
        internal static string ConditionCreateFailed {
            get {
                return ResourceManager.GetString("ConditionCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete condition..
        /// </summary>
        internal static string ConditionDeleteFailed {
            get {
                return ResourceManager.GetString("ConditionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create condition translation..
        /// </summary>
        internal static string ConditionTranslationCreateFailed {
            get {
                return ResourceManager.GetString("ConditionTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete condition translation..
        /// </summary>
        internal static string ConditionTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("ConditionTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update condition translation..
        /// </summary>
        internal static string ConditionTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("ConditionTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update condition..
        /// </summary>
        internal static string ConditionUpdateFailed {
            get {
                return ResourceManager.GetString("ConditionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create currency..
        /// </summary>
        internal static string CurrencyCreateFailed {
            get {
                return ResourceManager.GetString("CurrencyCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete currency..
        /// </summary>
        internal static string CurrencyDeleteFailed {
            get {
                return ResourceManager.GetString("CurrencyDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update currency..
        /// </summary>
        internal static string CurrencyUpdateFailed {
            get {
                return ResourceManager.GetString("CurrencyUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create favorite..
        /// </summary>
        internal static string FavoriteCreateFailed {
            get {
                return ResourceManager.GetString("FavoriteCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete favorite..
        /// </summary>
        internal static string FavoriteDeleteFailed {
            get {
                return ResourceManager.GetString("FavoriteDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update favorite..
        /// </summary>
        internal static string FavoriteUpdateFailed {
            get {
                return ResourceManager.GetString("FavoriteUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create image..
        /// </summary>
        internal static string ImageCreateFailed {
            get {
                return ResourceManager.GetString("ImageCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete image..
        /// </summary>
        internal static string ImageDeleteFailed {
            get {
                return ResourceManager.GetString("ImageDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update image..
        /// </summary>
        internal static string ImageUpdateFailed {
            get {
                return ResourceManager.GetString("ImageUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload image..
        /// </summary>
        internal static string ImageUploadFailed {
            get {
                return ResourceManager.GetString("ImageUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create product type..
        /// </summary>
        internal static string ProductTypeCreateFailed {
            get {
                return ResourceManager.GetString("ProductTypeCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete product type..
        /// </summary>
        internal static string ProductTypeDeleteFailed {
            get {
                return ResourceManager.GetString("ProductTypeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create product type translation..
        /// </summary>
        internal static string ProductTypeTranslationCreateFailed {
            get {
                return ResourceManager.GetString("ProductTypeTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete product type translation..
        /// </summary>
        internal static string ProductTypeTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("ProductTypeTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update product type translation..
        /// </summary>
        internal static string ProductTypeTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("ProductTypeTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update product type..
        /// </summary>
        internal static string ProductTypeUpdateFailed {
            get {
                return ResourceManager.GetString("ProductTypeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create region..
        /// </summary>
        internal static string RegionCreateFailed {
            get {
                return ResourceManager.GetString("RegionCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete region..
        /// </summary>
        internal static string RegionDeleteFailed {
            get {
                return ResourceManager.GetString("RegionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create region translation..
        /// </summary>
        internal static string RegionTranslationCreateFailed {
            get {
                return ResourceManager.GetString("RegionTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete region translation..
        /// </summary>
        internal static string RegionTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("RegionTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update region translation..
        /// </summary>
        internal static string RegionTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("RegionTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update region..
        /// </summary>
        internal static string RegionUpdateFailed {
            get {
                return ResourceManager.GetString("RegionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create role..
        /// </summary>
        internal static string RoleCreateFailed {
            get {
                return ResourceManager.GetString("RoleCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete role..
        /// </summary>
        internal static string RoleDeleteFailed {
            get {
                return ResourceManager.GetString("RoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update role..
        /// </summary>
        internal static string RoleUpdateFailed {
            get {
                return ResourceManager.GetString("RoleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete role..
        /// </summary>
        internal static string UserDeleteFailed {
            get {
                return ResourceManager.GetString("UserDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update role..
        /// </summary>
        internal static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
    }
}
