//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShagOxServer.Application.Resources.EntityErrorResourcess {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntityErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityErrorResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShagOxServer.Application.Resources.EntityErrorResourcess.EntityErrorResources", typeof(EntityErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create advertisement..
        /// </summary>
        internal static string AdvertisementCreateFailed {
            get {
                return ResourceManager.GetString("AdvertisementCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete advertisement.
        /// </summary>
        internal static string AdvertisementDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertisementDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update advertisement..
        /// </summary>
        internal static string AdvertisementUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertisementUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create status..
        /// </summary>
        internal static string AdvertStatusCreateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete status..
        /// </summary>
        internal static string AdvertStatusDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertStatusDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create status translation..
        /// </summary>
        internal static string AdvertStatusTranslationCreateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete status translation..
        /// </summary>
        internal static string AdvertStatusTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("AdvertStatusTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update status translation..
        /// </summary>
        internal static string AdvertStatusTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update status..
        /// </summary>
        internal static string AdvertStatusUpdateFailed {
            get {
                return ResourceManager.GetString("AdvertStatusUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create attribute definition..
        /// </summary>
        internal static string AttributeDefinitionCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete attribute definition..
        /// </summary>
        internal static string AttributeDefinitionDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create attribute definition translation..
        /// </summary>
        internal static string AttributeDefinitionTranslationCreateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete attribute definition translation..
        /// </summary>
        internal static string AttributeDefinitionTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update attribute definition translation..
        /// </summary>
        internal static string AttributeDefinitionTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update attribute definition..
        /// </summary>
        internal static string AttributeDefinitionUpdateFailed {
            get {
                return ResourceManager.GetString("AttributeDefinitionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create avatar..
        /// </summary>
        internal static string AvatarCreateFailed {
            get {
                return ResourceManager.GetString("AvatarCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete avatar..
        /// </summary>
        internal static string AvatarDeleteFailed {
            get {
                return ResourceManager.GetString("AvatarDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update avatar..
        /// </summary>
        internal static string AvatarUpdateFailed {
            get {
                return ResourceManager.GetString("AvatarUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create basket attribute..
        /// </summary>
        internal static string BasketAttributeCreateFailed {
            get {
                return ResourceManager.GetString("BasketAttributeCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create delete attribute..
        /// </summary>
        internal static string BasketAttributeDeleteFailed {
            get {
                return ResourceManager.GetString("BasketAttributeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create update attribute..
        /// </summary>
        internal static string BasketAttributeUpdateFailed {
            get {
                return ResourceManager.GetString("BasketAttributeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create basket..
        /// </summary>
        internal static string BasketCreateFailed {
            get {
                return ResourceManager.GetString("BasketCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete basket..
        /// </summary>
        internal static string BasketDeleteFailed {
            get {
                return ResourceManager.GetString("BasketDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create basket item..
        /// </summary>
        internal static string BasketItemCreateFailed {
            get {
                return ResourceManager.GetString("BasketItemCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete basket item..
        /// </summary>
        internal static string BasketItemDeleteFailed {
            get {
                return ResourceManager.GetString("BasketItemDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update basket item..
        /// </summary>
        internal static string BasketItemUpdateFailed {
            get {
                return ResourceManager.GetString("BasketItemUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update basket..
        /// </summary>
        internal static string BasketUpdateFailed {
            get {
                return ResourceManager.GetString("BasketUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create category..
        /// </summary>
        internal static string CategoryCreateFailed {
            get {
                return ResourceManager.GetString("CategoryCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete category..
        /// </summary>
        internal static string CategoryDeleteFailed {
            get {
                return ResourceManager.GetString("CategoryDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create category translation..
        /// </summary>
        internal static string CategoryTranslationCreateFailed {
            get {
                return ResourceManager.GetString("CategoryTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete category translation..
        /// </summary>
        internal static string CategoryTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("CategoryTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update category translation..
        /// </summary>
        internal static string CategoryTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("CategoryTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update category..
        /// </summary>
        internal static string CategoryUpdateFailed {
            get {
                return ResourceManager.GetString("CategoryUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create city..
        /// </summary>
        internal static string CityCreateFailed {
            get {
                return ResourceManager.GetString("CityCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete city..
        /// </summary>
        internal static string CityDeleteFailed {
            get {
                return ResourceManager.GetString("CityDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create city translation..
        /// </summary>
        internal static string CityTranslationCreateFailed {
            get {
                return ResourceManager.GetString("CityTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete city translation..
        /// </summary>
        internal static string CityTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("CityTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update city translation..
        /// </summary>
        internal static string CityTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("CityTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update city..
        /// </summary>
        internal static string CityUpdateFailed {
            get {
                return ResourceManager.GetString("CityUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create condition..
        /// </summary>
        internal static string ConditionCreateFailed {
            get {
                return ResourceManager.GetString("ConditionCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete condition..
        /// </summary>
        internal static string ConditionDeleteFailed {
            get {
                return ResourceManager.GetString("ConditionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create condition translation..
        /// </summary>
        internal static string ConditionTranslationCreateFailed {
            get {
                return ResourceManager.GetString("ConditionTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete condition translation..
        /// </summary>
        internal static string ConditionTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("ConditionTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update condition translation..
        /// </summary>
        internal static string ConditionTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("ConditionTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update condition..
        /// </summary>
        internal static string ConditionUpdateFailed {
            get {
                return ResourceManager.GetString("ConditionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create currency..
        /// </summary>
        internal static string CurrencyCreateFailed {
            get {
                return ResourceManager.GetString("CurrencyCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete currency..
        /// </summary>
        internal static string CurrencyDeleteFailed {
            get {
                return ResourceManager.GetString("CurrencyDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update currency..
        /// </summary>
        internal static string CurrencyUpdateFailed {
            get {
                return ResourceManager.GetString("CurrencyUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create favorite..
        /// </summary>
        internal static string FavoriteCreateFailed {
            get {
                return ResourceManager.GetString("FavoriteCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete favorite..
        /// </summary>
        internal static string FavoriteDeleteFailed {
            get {
                return ResourceManager.GetString("FavoriteDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update favorite..
        /// </summary>
        internal static string FavoriteUpdateFailed {
            get {
                return ResourceManager.GetString("FavoriteUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create image..
        /// </summary>
        internal static string ImageCreateFailed {
            get {
                return ResourceManager.GetString("ImageCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete image..
        /// </summary>
        internal static string ImageDeleteFailed {
            get {
                return ResourceManager.GetString("ImageDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update image..
        /// </summary>
        internal static string ImageUpdateFailed {
            get {
                return ResourceManager.GetString("ImageUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create product type..
        /// </summary>
        internal static string ProductTypeCreateFailed {
            get {
                return ResourceManager.GetString("ProductTypeCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete product type..
        /// </summary>
        internal static string ProductTypeDeleteFailed {
            get {
                return ResourceManager.GetString("ProductTypeDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create product type translation..
        /// </summary>
        internal static string ProductTypeTranslationCreateFailed {
            get {
                return ResourceManager.GetString("ProductTypeTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete product type translation..
        /// </summary>
        internal static string ProductTypeTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("ProductTypeTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update product type translation..
        /// </summary>
        internal static string ProductTypeTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("ProductTypeTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update product type..
        /// </summary>
        internal static string ProductTypeUpdateFailed {
            get {
                return ResourceManager.GetString("ProductTypeUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create region..
        /// </summary>
        internal static string RegionCreateFailed {
            get {
                return ResourceManager.GetString("RegionCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete region..
        /// </summary>
        internal static string RegionDeleteFailed {
            get {
                return ResourceManager.GetString("RegionDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create region translation..
        /// </summary>
        internal static string RegionTranslationCreateFailed {
            get {
                return ResourceManager.GetString("RegionTranslationCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete region translation..
        /// </summary>
        internal static string RegionTranslationDeleteFailed {
            get {
                return ResourceManager.GetString("RegionTranslationDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update region translation..
        /// </summary>
        internal static string RegionTranslationUpdateFailed {
            get {
                return ResourceManager.GetString("RegionTranslationUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update region..
        /// </summary>
        internal static string RegionUpdateFailed {
            get {
                return ResourceManager.GetString("RegionUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create role..
        /// </summary>
        internal static string RoleCreateFailed {
            get {
                return ResourceManager.GetString("RoleCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete role..
        /// </summary>
        internal static string RoleDeleteFailed {
            get {
                return ResourceManager.GetString("RoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update role..
        /// </summary>
        internal static string RoleUpdateFailed {
            get {
                return ResourceManager.GetString("RoleUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete role..
        /// </summary>
        internal static string UserDeleteFailed {
            get {
                return ResourceManager.GetString("UserDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update role..
        /// </summary>
        internal static string UserUpdateFailed {
            get {
                return ResourceManager.GetString("UserUpdateFailed", resourceCulture);
            }
        }
    }
}
