//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShagOxServer.Application.Resources.Verifications.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VerificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerificationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShagOxServer.Application.Resources.Verifications.Core.VerificationResources", typeof(VerificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already confirmed..
        /// </summary>
        internal static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during Code generation..
        /// </summary>
        internal static string FailedToGenerateVerificationCode {
            get {
                return ResourceManager.GetString("FailedToGenerateVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send verification email..
        /// </summary>
        internal static string FailedToSendVerificationEmail {
            get {
                return ResourceManager.GetString("FailedToSendVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send verification SMS..
        /// </summary>
        internal static string FailedToSendVerificationSms {
            get {
                return ResourceManager.GetString("FailedToSendVerificationSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have an email..
        /// </summary>
        internal static string NoUserEmail {
            get {
                return ResourceManager.GetString("NoUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have an phone..
        /// </summary>
        internal static string NoUserPhone {
            get {
                return ResourceManager.GetString("NoUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending email not found..
        /// </summary>
        internal static string PendingEmailNotFound {
            get {
                return ResourceManager.GetString("PendingEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending password not found..
        /// </summary>
        internal static string PendingPasswordNotFound {
            get {
                return ResourceManager.GetString("PendingPasswordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending phone not found..
        /// </summary>
        internal static string PendingPhoneNotFound {
            get {
                return ResourceManager.GetString("PendingPhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone already confirmed..
        /// </summary>
        internal static string PhoneAlreadyConfirmed {
            get {
                return ResourceManager.GetString("PhoneAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported verification purpose..
        /// </summary>
        internal static string UnsupportedVerificationPurpose {
            get {
                return ResourceManager.GetString("UnsupportedVerificationPurpose", resourceCulture);
            }
        }
    }
}
